name: Test to Main
permissions:
  contents: read
  pull-requests: write
on:
  workflow_dispatch:
  schedule:
    - cron: '40 17 */7 * *'
  
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d %b %Y')"
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: test
      - name: Abort if no differences between branches
        run: |
          git fetch origin main
          if git diff --quiet origin/main...origin/test; then
            echo "No changes to PR. Skipping."
            exit 0
          fi          
      - name: create pull request
        run: gh pr create -B main -H test --title 'Release ${{ steps.date.outputs.date }} Test to Main' --body 'Created by Github action' 
          || gh pr edit -B main --title 'Release ${{ steps.date.outputs.date }} Test to Main' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
